apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cnpg-backup-s3-credentials-store
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ $.Release.Namespace }}
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: {{ $.Release.Namespace }}
      auth:
        serviceAccount:
          name: cnpg-backup-s3-credentials-store
          namespace: {{ $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnpg-backup-s3-credentials-store
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["cnpg-backup-s3-credentials"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnpg-backup-s3-credentials-store
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnpg-backup-s3-credentials-store
subjects:
- kind: ServiceAccount
  name: cnpg-backup-s3-credentials-store
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cnpg-backup-s3-credentials-store
  apiGroup: rbac.authorization.k8s.io
