apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: cnpg-backup-s3-credentials
spec:
  length: 42
  symbolCharacters: ""
  symbols: 0
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backup-s3-credentials
spec:
  refreshInterval: 0s
  target:
    name: cnpg-backup-s3-credentials
  dataFrom:
  - sourceRef:
       generatorRef:
         apiVersion: generators.external-secrets.io/v1alpha1
         kind: Password
         name: cnpg-backup-s3-credentials
    rewrite:
    - regexp:
        source: "(.*)"
        target: "accessKey"

  - sourceRef:
       generatorRef:
         apiVersion: generators.external-secrets.io/v1alpha1
         kind: Password
         name: cnpg-backup-s3-credentials
    rewrite:
    - regexp:
        source: "(.*)"
        target: "secretKey"
