apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.seaweedfs.secret.name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-backup-s3-credentials-store
  target:
    name: {{ .Values.seaweedfs.secret.name }}
    template:
      engineVersion: v2
      data:
        seaweedfs_s3_config.json: |
          {
            "identities": [
              {
                "name": "admin",
                "actions": ["Admin"],
                "credentials": [
                  {
                    "accessKey": "{{ `{{ .accessKey }}` }}",
                    "secretKey": "{{ `{{ .secretKey }}` }}"
                  }
                ]
              }
            ]
          }
  data:
  - secretKey: accessKey
    remoteRef:
      key: local-backup-s3-credentials
      property: accessKey

  - secretKey: secretKey
    remoteRef:
      key: local-backup-s3-credentials
      property: secretKey
