{{ include "shared.backups.tpl" (dict
    "backups" .Values.backups
    "restores" .Values.restores
    "bucket" (dict "name" "bucket-name")
    "disable" (dict "schedule" true)
) }}

{{ range $index, $backup := .Values.backups }}
{{- include "shared.schedule.tpl" (dict
    "backup" $backup
    "bucket" (dict "name" "bucket-name")
    "namePostfix" "test"
    "override" (dict "backup" "wireguard.schedule.backup.override")
) }}
---
{{ end }}

{{ define "wireguard.schedule.backup.override" }}
podSecurityContext:
  runAsUser: 0
  fsGroup: 999
  fsGroupChangePolicy: OnRootMismatch

labelSelectors:
  - matchExpressions:
    - key: next.wieman.cloud/workload
      operator: NotIn
      values:
        - nextcloud
{{ end }}
