apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wireguard
  name: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      nodeName: talos-worker-0
      containers:
      - name: wireguard
        {{ with .Values.images.wireguard.image -}}
        image: {{ .registry }}/{{ .repository }}:{{ .version }}
        {{ end -}}
        env:
        - name:  SERVERURL
          value: wireguard.{{ .Values.network.hostname }}
        - name: PEERS
          value: {{ .Values.vpn.peers | join "," | quote }}
        - name: PEERDNS
          value: {{ .Values.vpn.dns | join "," | quote }}
        - name: LOG_CONFS
          value: "false"
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: wireguard-config
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
  labels:
    app: wireguard
spec:
  type: NodePort
  selector:
    app: wireguard
  ports:
    - name: wireguard
      port: 51820
      targetPort: 51820
      protocol: UDP
      nodePort: 30000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
