apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wireguard
  name: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - image: linuxserver/wireguard:1.0.20250521
        name: wireguard
        env:
          SERVERURL: wireguard.{{ .Values.environment.hostname }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wireguard
  name: wireguard
spec:
  ports:
  - name: 51820
    port: 51820
    protocol: UDP
    targetPort: 51820
  selector:
    app: wireguard
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: UDPRoute
metadata:
  name: wireguard
spec:
  parentRefs:
    - name: {{ .Values.environment.gateway.name }}
      sectionName: {{ .Values.environment.gateway.listener }}
      namespace: {{ .Values.environment.gateway.namespace }}

  hostnames:
    - wireguard.{{ .Values.environment.hostname }}

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      backendRefs:
        - name: wireguard
          namespace: {{ .Release.Namespace }}
          port: 51820
