apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wireguard
  name: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - image: linuxserver/wireguard:1.0.20250521
        name: wireguard
        env:
        - name:  SERVERURL
          value: wireguard.{{ .Values.environment.hostname }}
        - name: PEERS
          value: 1
        - name: PEERDNS
          value: "1.1.1.1"
        - name: LOG_CONFS
          value: true
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
  labels:
    app: wireguard
  annotations:
    external-dns.alpha.kubernetes.io/hostname: wireguard.{{ .Values.environment.hostname }}
    external-dns.alpha.kubernetes.io/target: wieman.cloud
spec:
  type: LoadBalancer
  loadbalancerIp: 192.168.178.202
  ports:
  - port: 51820
    targetPort: 51820
    protocol: UDP
  selector:
    app: wireguard
