{{- range $index, $backup := .Values.k8up.backups }}
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: {{ $backup.name }}
  namespace: {{ $backup.namespace }}
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2

  labelSelectors:
    - matchExpressions:
      - key: wieman.cloud/backup
        operator: In
        values:
          - "true"

  backend:
    repoPasswordSecretRef:
      {{ toYaml $.Values.k8up.backend.repoPasswordSecretRef | nindent 6 }}
    s3:
      endpoint: https://{{ $.Values.seaweedfs.endpoint }}
      bucket: {{ $.Values.seaweedfs.bucket }}
      accessKeyIDSecretRef:
        name: {{ printf "%s-%s" $backup.name "s3-backup-secret" }}
        key: accessKey
      secretAccessKeySecretRef:
        name: {{ printf "%s-%s" $backup.name "s3-backup-secret" }}
        key: secretKey
{{- end }}
