{{- range $index, $backup := .Values.k8up.backups }}

{{- $schedule := default dict $backup.schedule }}
{{- $retention := default dict $backup.retention }}

apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: {{ $backup.name }}
  namespace: {{ $backup.namespace }}
spec:
  backend:
    repoPasswordSecretRef:
      {{ toYaml $.Values.k8up.backend.repoPasswordSecretRef | nindent 6 }}
    s3:
      endpoint: https://{{ $.Values.seaweedfs.endpoint }}
      bucket: {{ $.Values.seaweedfs.bucket }}
      accessKeyIDSecretRef:
        name: backup-s3-secret
        key: accessKey
      secretAccessKeySecretRef:
        name: backup-s3-secret
        key: secretKey

  backup:
    schedule: {{ $schedule.backup | default $.Values.k8up.default.schedule.backup | quote }}
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 0
    podSecurityContext:
      runAsUser: 0
      fsGroup: 999
      fsGroupChangePolicy: OnRootMismatch

  check:
    schedule: {{ $schedule.check | default $.Values.k8up.default.schedule.check | quote }}

  prune:
    schedule: {{ $schedule.prune | default $.Values.k8up.default.schedule.prune | quote }}
    retention:
      keepLast: {{ $retention.keepLast | default $.Values.k8up.default.retention.keepLast }}
      keepDaily: {{ $retention.keepDaily | default $.Values.k8up.default.retention.keepDaily }}
---
{{- end }}
