{{- if not (lookup "v1" "Secret" .Release.Namespace .Values.seaweedfs.secret.name) }}

{{- $password := randAlphaNum 50 -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.k8up.backend.repoPasswordSecretRef.name }}
type: Opaque
stringData:
  {{ .Values.k8up.backend.repoPasswordSecretRef.key }}: {{ $password | quote }}

{{- end }}
