apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.k8up.backend.repoPasswordSecretRef.name }}
  labels:
    wieman.cloud/random-secret: "true"
type: Opaque
stringData:
  {{ .Values.k8up.backend.repoPasswordSecretRef.key }}: {{ randAlphaNum 50 | quote }}
