{{- $accessKey := randAlphaNum 50 -}}
{{- $secretKey := randAlphaNum 50 -}}
{{- $deployAccessKey := randAlphaNum 50 -}}
{{- $deploySecretKey := randAlphaNum 50 -}}


apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.seaweedfs.secret.name }}
  labels:
    wieman.cloud/random-secret: "true"
type: Opaque
stringData:
  seaweedfs_s3_config.json: |
    {
      "identities": [
        {
          "actions": [
            "Read",
            "List",
            "Write"
          ],
          "credentials": [
            {
              "accessKey": {{ $accessKey | quote }},
              "secretKey": {{ $secretKey | quote }}
            }
          ],
          "name": "k8up-s3-user"
        },
        {
          "actions": [
            "Admin"
          ],
          "credentials": [
            {
              "accessKey": {{ $deployAccessKey | quote }},
              "secretKey": {{ $deploySecretKey | quote }}
            }
          ],
          "name": "deploy-s3-user"
        }
      ]
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: deploy-s3-secret
  labels:
    wieman.cloud/random-secret: "true"
type: Opaque
stringData:
  accessKey: {{ $deployAccessKey | quote }}
  secretKey: {{ $deploySecretKey | quote }}
---
# Copy secrets to other namespaces for Backups and Restores
{{- range $index, $backup := .Values.k8up.backups }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $backup.name "s3-backup-secret" }}
  namespace: {{ $backup.namespace }}
  labels:
    wieman.cloud/random-secret: "true"
type: Opaque
stringData:
  accessKey: {{ $accessKey | quote }}
  secretKey: {{ $secretKey | quote }}
---
{{- end }}
{{- range $index, $restore := .Values.k8up.restores }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $restore.name "s3-restore-secret" }}
  namespace: {{ $restore.namespace }}
  labels:
    wieman.cloud/random-secret: "true"
type: Opaque
stringData:
  accessKey: {{ $accessKey | quote }}
  secretKey: {{ $secretKey | quote }}
{{- end }}
