{{- if eq .Values.externalsecrets.backup "Push" }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: tfstate-default-state-backup
spec:
  updatePolicy: Replace
  deletionPolicy: None
  refreshInterval: 2m
  secretStoreRefs:
    - name: aws
      kind: ClusterSecretStore
  selector:
    secret:
      name: tfstate-default-state
  data:
    - match:
        remoteRef:
          remoteKey: k8up-tfstate-default-state-backup
{{- end }}
{{- if eq .Values.externalsecrets.backup "Pull" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tfstate-default-state-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws
  target:
    name: tfstate-default-state
  data:
    - secretKey: tfstate
      remoteRef:
        key: k8up-tfstate-default-state-backup
        property: tfstate

{{- end }}
