apiVersion: batch/v1
kind: CronJob
metadata:
  name: tofudeployer
spec:
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      name: tofudeployer
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: tofudeployer
            {{- with .Values.tofudeployer.image }}
            image: {{ .registry }}/{{ .repository }}:{{ .version }}
            {{- end }}
            env:
            - name: DRY_RUN
              value: "false"
            - name: REPOSITORY_URL
              value: {{ .Values.targetRepository.url }}
            - name: REPOSITORY_BRANCH
              value: {{ .Values.targetRepository.branch }}
            - name: TOFU_PATH
              value: infrastructure/k8up/tofu
          restartPolicy: Never
  schedule: 0/3 * * * * *
