apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: local-backup-s3
spec:
  configuration:
    destinationPath: s3://wiecloud-nextcloud-postgres-backups/
    endpointURL: https://k8up.s3.wieman.cloud

    s3Credentials:
      accessKeyId:
        name: local-backup-s3-credentials
        key: accessKey
      secretAccessKey:
        name: local-backup-s3-credentials
        key: secretKey

    wal:
      compression: gzip

    retentionPolicy: "14d"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: local
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: nextcloud-postgres-cluster

  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
