apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgres-cluster
spec:
  instances: 1

  bootstrap:
    initdb:
      database: nextcloud
      import:
        type: microservice
        databases:
          - nextcloud
        source:
          externalCluster: postgres-sts

    # recovery:
    #   source: source

  storage:
    size: 2Gi

  externalClusters:
    - name:  postgres-sts
      connectionParameters:
        host: postgresql-db-service
        user: admin
        dbname: nextcloud
      password:
        name: nextcloud-db-credentials
        key: password
  # - name: source
  #   plugin:
  #     name: barman-cloud.cloudnative-pg.io
  #     parameters:
  #       barmanObjectName: local-backup-s3
  #       serverName: cluster-example
