apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgres-cluster
spec:
  instances: 1

  bootstrap:
    initdb:
      database: nextcloud

    # recovery:
    #   source: source

  storage:
    size: 2Gi

  # externalClusters:
  # - name: source
  #   plugin:
  #     name: barman-cloud.cloudnative-pg.io
  #     parameters:
  #       barmanObjectName: local-backup-s3
  #       serverName: cluster-example
