apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nextcloud.externalDatabase.host }}
spec:
  selector:
    app: postgresql-db
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: {{ .Values.nextcloud.externalDatabase.host }}
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-db
  template:
    metadata:
      labels:
        app: postgresql-db
      annotations:
        k8up.io/backupcommand: sh -c 'PGDATABASE="$POSTGRES_DB" PGUSER="$POSTGRES_USER" PGPASSWORD="$POSTGRES_PASSWORD" pg_dump --clean'
        k8up.io/file-extension: .sql
    spec:
      containers:
        - name: postgresql-db
          image: postgres:18.1
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.nextcloud.externalDatabase.existingSecret.secretName }}
                  key: {{ .Values.nextcloud.externalDatabase.existingSecret.usernameKey }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.nextcloud.externalDatabase.existingSecret.secretName }}
                  key: {{ .Values.nextcloud.externalDatabase.existingSecret.passwordKey }}
            - name: POSTGRES_DB
              value: nextcloud
            - name: PGDATA
              value: /data/pgdata
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-postgresql-db-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-postgresql-db-0
  labels:
    next.wieman.cloud/workload: "postgres"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
