minecraft:
  image:
    tag: java17
  minecraftServer:
    eula: true
    motd: "§l§5WiemanServer§r

      §rWelcome to my server!"
    memory: 9G

    worldSaveName: example
    version: "0.0.0"
    difficulty: hard
    maxPlayers: 20
    maxBuildHeight: 256
    spawnProtection: 0
    viewDistance: 20

    type: EXAMPLE
    vanillaTweaksShareCodes: []
    modrinth:
      projects: []

    autoCurseForge:
      apiKey:
        existingSecret: curseforge-api-token
        secretKey: api-token
      # Link to modpack in general or a specific file
      pageUrl: ""
      zipUrl: ""

      # List of project slugs or IDs to be excluded from modpack, useful if mod is incorrectly marked as server side
      excludeMods: []

      # List of project slugs or IDs to be included in modpack, useful if mod is incorrectly marked as client side only
      includeMods: []
      parallelDownloads: 4

    rcon:
      enabled: true

    voicechat:
      enabled: false

  extraEnv:
    ENABLE_WHITELIST: true
    CURSEFORGE_FILES: ""

  persistence:
    annotations:
      k8up.io/backup: "true"
    dataDir:
      enabled: true
      Size: 10Gi

  mcbackup:
    enabled: true
    pauseIfNoPlayers: true

    backupInterval: 4h
    pruneBackupsDays: 2

    extraEnv:
      PRE_BACKUP_SCRIPT: |
        DATE_LOG="§l§d$(TZ="Europe/Amsterdam" date +"[%Y/%m/%d %H:%M:%S]")§r§e"

        rcon-cli bluemap stop
        rcon-cli tellraw @a "{\"text\": \"$DATE_LOG Starting backup...\"}" &>/dev/null &
      POST_BACKUP_SCRIPT: |
        DATE_LOG="§l§d$(TZ="Europe/Amsterdam" date +"[%Y/%m/%d %H:%M:%S]")§r§e"
        NEXT_BACKUP_LOG="§a§u$(TZ="Europe/Amsterdam" date -d "$(echo $BACKUP_INTERVAL | sed 's/h$//') hours" +"%H:%M")"

        rcon-cli bluemap start
        rcon-cli tellraw @a "{\"text\": \"$DATE_LOG Backup complete, Next backup at: $NEXT_BACKUP_LOG\"}" &>/dev/null &

    persistence:
      backupDir:
        enabled: true
        Size: 20Gi

    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi

  resources:
    limits:
      memory: 15Gi
    requests:
      cpu: 2
      memory: 10Gi

  extraVolumes:
    - volumeMounts:
        - name: whitelist
          mountPath: /data/whitelist.json
          subPath: whitelist.json
          readOnly: true
        - name: bluemap-core-config
          mountPath: /data/config/bluemap/core.conf
          subPath: core.conf
          readOnly: true

      volumes:
        - name: whitelist
          configMap:
            name: whitelist
            items:
              - key: whitelist.json
                path: whitelist.json
        - name: bluemap-core-config
          configMap:
            name: bluemap-core-config
            items:
              - key: core.conf
                path: core.conf

  initContainers:
    - name: download-zip
      image: curlimages/curl:8.20.0
      env:
        - name: ZIP_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: zip
      command: [ "/bin/sh", "-c" ]
      args:
        - |
          set -e

          mkdir -p /data/zip

          if [ -z "$ZIP_URL" ]; then
            echo "No ZIP URL provided, skipping download."
            exit 0
          fi

          echo "Downloading ZIP from: $ZIP_URL"
          curl -L "$ZIP_URL" -o /data/zip/server.zip

          echo "Download complete:"
          ls -lah /data/zip

      volumeMounts:
        - name: datadir
          mountPath: /data

network:
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example

images:
  rconcli:
    image:
      registry: example.com
      repository: tools/rconcli
      version: 0.0.0
