nextcloud:
  nodeSelector:
    topology.kubernetes.io/zone: gigabyte-pve-0

  phpClientHttpsFix:
    enabled: true
    protocol: https

  persistence:
    enabled: true
    size: 50Gi
    annotations:
      k8up.io/backup: "true"
    labels:
      next.wieman.cloud/workload: "nextcloud"

  internalDatabase:
    enabled: false
  externalDatabase:
    enabled: true
    type: postgresql
    host: nextcloud-postgres-cluster-rw
    existingSecret:
      enabled: true
      secretName: nextcloud-postgres-cluster-app
      usernameKey: username
      passwordKey: password

  nextcloud:
    host: example.com

    apps:
      - name: user_oidc
        enabled: true

      - name: contacts
        enabled: true

      - name: deck
        enabled: true

      - name: maps
        enabled: true

      - name: calendar
        enabled: true

      - name: whiteboard
        enabled: true

      - name: notes
        enabled: true

      - name: memories
        enabled: true

      - name: forms
        enabled: true

      - name: tasks
        enabled: true

      - name: drawio
        enabled: true

      - name: metadata
        enabled: true

      - name: onlyoffice
        enabled: true

    configs:
      setup.config.php: |-
        <?php
        $CONFIG = array (
          'skeletondirectory' => '',
        );

    extraVolumes:
      - name: configure
        configMap:
          name: configure
          defaultMode: 493
          items:
            - key: configure.sh
              path: configure.sh
      - name: nextcloud-client-secret
        secret:
          secretName: nextcloud-client-secret
          items:
            - key: secret
              path: nextcloud-client-secret

    extraVolumeMounts:
      - name: configure
        mountPath: /docker-entrypoint-hooks.d/post-installation/configure.sh
        subPath: configure.sh
        readOnly: true
      - name: configure
        mountPath: /docker-entrypoint-hooks.d/before-starting/configure.sh
        subPath: configure.sh
        readOnly: true

      - name: nextcloud-client-secret
        mountPath: /var/run/secrets/nextcloud-client-secret
        subPath: nextcloud-client-secret
        readOnly: true

network:
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example

auth:
  oidc:
    provider: Example
    endpoint: https://example.com

cnpg:
  restore: false
