environment:
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example
  oidc:
    provider: Example
    endpoint: https://example.com

nextcloud:
  phpClientHttpsFix:
    enabled: true
    protocol: https

  nextcloud:
    host: example.com

    apps:
    - name: user_oidc
      enabled: true

    configs:
      setup.config.php: |-
        <?php
        $CONFIG = array (
          'skeletondirectory' => '',
        );

    # objectStore:
    #   s3:
    #     name: seaweedfs-nextcloud
    #     enabled: true
    #     host: next.s3.example.com
    #     bucket: nextcloud-bucket
    #     autoCreate: true
    #     existingSecret: s3-secret
    #     secretKeys:
    #       accessKey: "access_key"
    #       secretKey: "secret_key"

    extraVolumes:
    - name: app-install
      configMap:
        name: app-install
        defaultMode: 493
        items:
        - key: app-install.sh
          path: app-install.sh
    - name: oidc-setup
      configMap:
        name: oidc-setup
        defaultMode: 493
        items:
        - key: oidc-setup.sh
          path: oidc-setup.sh
    - name: nextcloud-client-secret
      secret:
        secretName: nextcloud-client-secret
        items:
        - key: secret
          path: nextcloud-client-secret

    extraVolumeMounts:
    - name: app-install
      mountPath: /docker-entrypoint-hooks.d/post-installation/app-install.sh
      subPath: app-install.sh
      readOnly: true
    - name: oidc-setup
      mountPath: /docker-entrypoint-hooks.d/post-installation/oidc-setup.sh
      subPath: oidc-setup.sh
      readOnly: true
    - name: nextcloud-client-secret
      mountPath: /var/run/secrets/nextcloud-client-secret
      subPath: nextcloud-client-secret
      readOnly: true
