environment:
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example
  oidc:
    provider: Example
    endpoint: https://example.com

kube-prometheus-stack: {}
