apiVersion: wieman.cloud/v1
kind: App
metadata:
  name: carnaval
spec:
  image: docker.io/wiemanboy/carnaval:0.0.5

  route:
    hostnames:
      - carnaval.lol
      - www.carnaval.lol

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 2m
      memory: 128Mi
