apiVersion: wieman.cloud/v1
kind: App
metadata:
  name: wiemansite
spec:
  image: docker.io/wiemanboy/wiemansite

  route:
    hostnames:
      - wiemanboy.com
      - www.wiemanboy.com
      - jarnowieman.com
      - www.jarnowieman.com
      - jarnowieman.nl
      - www.jarnowieman.nl
    targetPort: 3000

  resources:
    limits:
      memory: 252Mi
    requests:
      cpu: 1m
      memory: 126Mi
