environment:
  hostname: wieman.cloud
  gateway:
    name: traefik-gateway
    listener: websecure
    namespace: gateway
    authentication:
      basicAuth:
        name: basic-auth
        secret:
          name: server-auth-secret
  oidc:
    provider: Keycloak
    endpoint: https://keycloak.wieman.cloud/realms/wiecloud

backups:
  - name: local
    s3:
      endpoint: https://k8up.s3.wieman.cloud
      secret:
        name: backup-s3-secret
        accessKey: accessKey
        secretKey: secretKey
    repo:
      secret:
        name: repo-password-secret
        key: password
    default:
      schedule:
        backup: "0 12 * * *"
        check: "30 12 * * *"
        prune: "0 13 * * *"
      retention:
        keepLast: 5
        keepDaily: 14

vpn:
  peers:
    - pc
    - laptop
    - s24ultra
  dns:
    - "1.1.1.1"
    - "8.8.8.8"

targetRepository:
  url: https://github.com/wiemanboy/WieCloud.git
  branch: master

applications:
  minecraft:
    deploy: true
    version: 1.0.1
    restores:
      - name: minecraft-local-restore
        enabled: false
        fromBackup: local
        snapshot: ""
        claim:
          name: minecraft-datadir
    world:
      name: minecraft-for-the-gurls
      version: 1.20.1
    server:
      launcher: AUTO_CURSEFORGE
      version: java21
    bluemap:
      file: https://www.curseforge.com/minecraft/mc-mods/bluemap/files/7057487
    mods:
      vanillaTweaks: []
      modrinth:
        projects: []
      curseforge:
        zip:
          deploy: true
          file: https://next.wieman.cloud/public.php/dav/files/HxMebrnGZSXoSQF/Jarno%20server-1.2.0.zip
        pageUrl: ""
        excludeMods: []
        includeMods: []

  nextcloud:
    deploy: true
    version: 0.1.2
    restores:
      - name: nextcloud-local-restore
        enabled: false
        fromBackup: local
        snapshot: ""
        claim:
          name: nextcloud-nextcloud
      - name: postgresql-local-restore
        enabled: false
        fromBackup: local
        snapshot: ""
        claim:
          name: data-postgresql-db-0

  website:
    deploy: true
    namespace: website

  server: https://kubernetes.default.svc
  repository: harbor.wieman.cloud/applications

infrastructure:
  argocd:
    deploy: true
    version: 0.3.1-implement-external-secrets-676e2bb

  certmanager:
    deploy: true
    version: 0.2.3
    certificate:
      email: wiemanboy@gmail.com
      hostnames:
        - "wieman.cloud"
        - "*.wieman.cloud"
        - "*.s3.wieman.cloud"
        - "wiemanboy.com"
        - "*.wiemanboy.com"
        - "jarnowieman.com"
        - "*.jarnowieman.com"
        - "jarnowieman.nl"
        - "*.jarnowieman.nl"
        - "carnaval.lol"
        - "*.carnaval.lol"

  externaldns:
    deploy: true
    version: 0.0.7

  externalsecrets:
    deploy: true
    version: 0.0.0-implement-external-secrets-676e2bb

  harbor:
    deploy: true
    version: 1.2.0
    restores:
      - name: harbor-registry-local-restore
        enabled: false
        fromBackup: local
        snapshot: ""
        claim:
          name: harbor-registry
      - name: harbor-database-local-restore
        enabled: false
        fromBackup: local
        snapshot: ""
        claim:
          name: database-data-harbor-database-0

  k8up:
    deploy: true
    version: 1.0.0-implement-external-secrets-676e2bb

  keycloak:
    deploy: true
    version: 1.1.1
    restores:
      - name: postgresql-local-restore
        enabled: false
        fromBackup: local
        snapshot: ""
        claim:
          name: data-postgresql-db-0

  longhorn:
    deploy: true
    version: 0.0.7

  metallb:
    deploy: true
    version: 0.0.9

  prometheus:
    deploy: true
    version: 0.0.1

  traefik:
    deploy: true
    version: 0.1.6

  seaweedfs:
    deploy: true
    version: 0.0.1

  wireguard:
    deploy: true
    version: 0.0.0

  server: https://kubernetes.default.svc
  repository: harbor.wieman.cloud/infrastructure

images:
  rconcli:
    image:
      registry: harbor.wieman.cloud
      repository: tools/rconcli
      version: 1.1.5

  tofudeployer:
    image:
      registry: harbor.wieman.cloud
      repository: products/tofudeployer
      version: 0.0.1
