environment:
  hostname: wieman.cloud
  gateway:
    name: traefik-gateway
    listener: websecure
    namespace: gateway
    authentication:
      basicAuth:
        name: basic-auth
        secret:
          name: server-auth-secret
  oidc:
    provider: Keycloak
    endpoint: https://keycloak.wieman.cloud/realms/infrastructure

applications:
  minecraft:
    deploy: true
    version: 0.5.0-implement-k8up-14aa929

  nextcloud:
    deploy: true
    version: 0.1.0-implement-k8up-14aa929

  website:
    deploy: true
    namespace: website

  server: https://kubernetes.default.svc
  repository: harbor.wieman.cloud/applications

infrastructure:
  argocd:
    deploy: true
    version: 0.2.5

  certmanager:
    deploy: true
    version: 0.2.2
    certificate:
      email: wiemanboy@gmail.com
      hostnames:
      - "wieman.cloud"
      - "*.wieman.cloud"
      - "*.s3.wieman.cloud"
      - "wiemanboy.com"
      - "*.wiemanboy.com"
      - "jarnowieman.com"
      - "*.jarnowieman.com"
      - "jarnowieman.nl"
      - "*.jarnowieman.nl"
      - "carnaval.lol"
      - "*.carnaval.lol"

  externaldns:
    deploy: true
    version: 0.0.6

  harbor:
    deploy: true
    version: 1.1.0-implement-k8up-14aa929

  k8up:
    deploy: true
    version: 0.0.0-implement-k8up-14aa929

    default:
      schedule:
        backup: "*/5 * * * *"
        check: "0 1 * * 1"
        prune: "0 1 * * 0"
      retention:
        keepLast: 5
        keepDaily: 14

    backups:
    - name: minecraft
      namespace: minecraft

    - name: nextcloud
      namespace: nextcloud

    - name: harbor
      namespace: harbor

    - name: keycloak
      namespace: keycloak

    - name: test
      namespace: default

    # - name: example-backup
    #   namespace: default
    #   schedule:
    #     backup: "*/5 * * * *"
    #     check: "0 1 * * 1"
    #     prune: "0 1 * * 0"
    #   retention:
    #     keepLast: 5
    #     keepDaily: 14

    # restores:
    # - name: example-restore
    #   namespace: default
    #   snapshot: example-snapshot # Defaults to latest
    #   claim:
    #     name: example-pvc
    #     deploy: true
    #     spec:
    #       accessModes:
    #         - ReadWriteOnce
    #       resources:
    #         requests:
    #           storage: 1Gi

  keycloak:
    deploy: true
    version: 1.1.0-implement-k8up-14aa929

  longhorn:
    deploy: true
    version: 0.0.6

  metallb:
    deploy: true
    version: 0.0.8

  prometheus:
    deploy: true
    version: 0.0.0

  traefik:
    deploy: true
    version: 0.1.5

  seaweedfs:
    deploy: true
    version: 0.0.0

  server: https://kubernetes.default.svc
  repository: harbor.wieman.cloud/infrastructure

images:
  rconcli:
    image:
      registry: harbor.wieman.cloud
      repository: tools/rconcli
      version: 1.1.3
