network:
  hostname: dev.wieman.cloud
  externalIp: 85.148.81.86
  ipPool:
    - 192.168.178.210 - 192.168.178.220
  gateway:
    certificate:
      hostnames:
        - "dev.wieman.cloud"
        - "*.dev.wieman.cloud"
        - "*.s3.dev.wieman.cloud"

auth:
  oidc:
    endpoint: https://keycloak.dev.wieman.cloud/realms/wiecloud


applications:
  minecraft:
    deploy: false

  nextcloud:
    deploy: false

  website:
    deploy: false

infrastructure:
  argocd:
    deploy: false

  certmanager:
    deploy: true

  cilium:
    deploy: true

  cnpg:
    deploy: true
    seaweedfs:
      backup:
        enabled: false
      restore:
        enabled: true
    restores:
      - name: seaweed-restore
        enabled: true
        fromBackup: aws
        snapshot: "36ee995b0f17a6e06f3f71b36d29f069df6209891eccc1d4cead2bd2b29e6d96"
        claim:
          name: seaweed-backup

  envoygateway:
    deploy: true

  externaldns:
    deploy: true

  externalsecrets:
    deploy: true

  harbor:
    deploy: false

  k8up:
    deploy: true

  keycloak:
    deploy: false

  kyverno:
    deploy: false

  longhorn:
    deploy: true

  metallb:
    deploy: false

  nodes:
    deploy: false

  prometheus:
    deploy: false

  seaweedfs:
    deploy: true

  wireguard:
    deploy: false
