# Source: wiecloud/templates/infrastructure/argocd.application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  source:
    chart: argocd
    repoURL: harbor.wieman.cloud/infrastructure
    targetRevision: 0.0.0
    helm:
      values: |
        environment: map[gateway:map[authentication:map[basicAuth:map[name:basic-auth secret:map[name:server-auth-secret]]] listener:websecure name:traefik-gateway namespace:gateway] hostname:wieman.cloud]
        argo-cd:
          configs:
            cm:
              url: https://argo.wieman.cloud
              oidc.config: |
                name: Keycloak
                issuer: https://keycloak.wieman.cloud/realms/infrastructure
                clientID: argocd
                clientSecret: $oidc.keycloak.clientSecret
                requestedScopes: ["openid", "profile", "email", "groups"]
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true