apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: {{ .Values.seaweedfs.name }}
spec:
  image: chrislusf/seaweedfs:latest
  master:
    replicas: 1
    volumeSizeLimitMB: 1024
    limits:
      memory: 64Mi
    requests:
      cpu: 1m
      memory: 32Mi

  volume:
    replicas: 1
    limits:
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi
      storage: 50Gi

  filer:
    replicas: 1
    persistence:
      enabled: true
      resources:
        requests:
          storage: 5Gi
    s3:
      enabled: true
      configSecret:
        name: {{ .Values.seaweedfs.secret.name }}
        key: seaweedfs_s3_config.json
    config: |
      [leveldb2]
      enabled = true
      dir = "/data/filerldb2"
    limits:
      memory: 256Mi
    requests:
      cpu: 5m
      memory: 128Mi

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.seaweedfs.name }}
spec:
  parentRefs:
    - name: {{ .Values.network.gateway.name }}
      sectionName: {{ .Values.network.gateway.listener }}
      namespace: {{ .Values.network.gateway.namespace }}

  hostnames:
    - {{ .Values.seaweedfs.endpoint }}

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      backendRefs:
        - name: "{{ .Values.seaweedfs.name }}-filer"
          namespace: {{ .Release.Namespace }}
          port: 8333
