seaweedfs:
  backup:
    enabled: true
  name: backup-s3
  endpoint: k8up.s3.example.com
  secret:
    name: cnpg-backup-s3-config

network:
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example
