apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.network.gateway.name }}
spec:
  gatewayClassName: default-envoy-gateway
  listeners:
    - name: {{ .Values.network.gateway.listener }}
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: letsencrypt-certificate
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
    - name:  minecraft
      protocol: TCP
      port: 25565
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: minecraft
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
spec:
  secretName: letsencrypt-certificate
  dnsNames: {{ toYaml .Values.network.gateway.certificate.hostnames | nindent 4 }}
  issuerRef: {{ toYaml .Values.network.gateway.certificate.issuerRef | nindent 4 }}
