apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.network.gateway.name }}
spec:
  gatewayClassName: default-envoy-gateway
  listeners:
    - name: {{ .Values.network.gateway.listener }}
      protocol: HTTP
      port: 8443
      tls:
        mode: Terminate
        certificateRefs:
          - name: letsencrypt-certificate
            kind: Certificate
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
spec:
  secretName: letsencrypt-secret
  dnsNames: {{ toYaml .Values.network.gateway.certificate.hostnames | nindent 4 }}
  issuerRef: {{ toYaml .Values.network.gateway.certificate.issuerRef | nindent 4 }}
