apiVersion: policies.kyverno.io/v1
kind: DeletingPolicy
metadata:
  name: cleanup-failed-jobs
  namespace: production
spec:
  schedule: '0 0 0/2 *'
  matchConstraints:
    resourceRules:
      - apiGroups: ['batch']
        apiVersions: ['v1']
        resources: ['jobs']
  conditions:
    - name: completed-failed-and-older-than-2h
      expression: >
        (
          object.status.conditions.exists(c, c.type == 'Complete' && c.status == 'True') ||
          object.status.conditions.exists(c, c.type == 'Failed' && c.status == 'True')
        )
        &&
        (
          object.metadata.creationTimestamp < time.now() - duration("2h")
        )
