apiVersion: policies.kyverno.io/v1
kind: MutatingPolicy
metadata:
  name: set-revision-history
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ['apps']
        apiVersions: ['v1']
        operations: ['CREATE', 'UPDATE']
        resources: ['deployments', 'statefulsets']
  mutations:
    - patchType: ApplyConfiguration
      applyConfiguration:
        expression: >
          Object{
            spec: {
              revisionHistoryLimit: 0
            }
          }
