name: Build <chart_name>

on:
  push:
    branches:
    - master
    paths:
    - <chart_path>**
    - .github/workflows/build_<chart_name>.yaml
    - .github/workflows/build.yaml
    - pipeline/build/scripts/**
  pull_request:
    branches:
    - master
    types:
    - ready_for_review
    - synchronize
    paths:
    - <chart_path>**
    - .github/workflows/build_<chart_name>.yaml
    - .github/workflows/build.yaml
    - pipeline/build/scripts/**
  workflow_dispatch:


jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      chart_name: <chart_name>
      chart_path: <chart_path>
      registry: <registry>
      repository: <repository>
    secrets:
      registry_username: ${{ secrets.OCI_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.OCI_REGISTRY_PASSWORD }}
