name: Build <chart_name>

on:
  push:
    branches:
      - master
    paths:
      - <chart_path>**
      - .github/workflows/build_<chart_name>.yaml
      - .github/workflows/package_push.yaml
      - pipeline/build/scripts/**
  pull_request:
    branches:
      - master
    paths:
      - <chart_path>**
      - .github/workflows/build_<chart_name>.yaml
      - .github/workflows/package_push.yaml
      - pipeline/build/scripts/**

jobs:
  package_and_push:
    name: Package and push
    uses: ./.github/workflows/package_push.yaml
    with:
      chart_name: <chart_name>
      chart_path: <chart_path>
      registry: <registry>
      repository: <repository>
    secrets:
      registry_username: ${{ secrets.OCI_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.OCI_REGISTRY_PASSWORD }}
