apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tofudeployer-client-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws
  target:
    name: tofudeployer-client-secret
  data:
    - secretKey: secret
      remoteRef:
        key: tofudeployer-client-secret
        property: secret
