apiVersion: apps/v1
kind: Deployment
metadata:
  name: satisfactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      containers:
        - name: satisfactory
          {{ with .Values.images.satisfactory.image -}}
          image: {{ .registry }}/{{ .repository }}:{{ .version }}
          {{ end -}}
          ports:
            - containerPort: 7777
              name: game-tcp
              protocol: TCP
            - containerPort: 7777
              name: game-udp
              protocol: UDP
          resources: {{ toYaml .Values.satisfactory.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /config
              name: satisfactory-config
            - mountPath: /config/gamefiles
              name: satisfactory-gamefiles
      securityContext:
        fsGroup: 1000
      volumes:
        - name: satisfactory-config
          persistentVolumeClaim:
            claimName: satisfactory-config
        - name: satisfactory-gamefiles
          persistentVolumeClaim:
            claimName: satisfactory-gamefiles
