apiVersion: v1
kind: Service
metadata:
  name: satisfactory
spec:
  ports:
    - name: game-tcp
      port: 7777
      protocol: TCP
      targetPort: game-tcp
    - name: game-udp
      port: 7777
      protocol: UDP
      targetPort: game-udp
  selector:
    app: satisfactory
  type: ClusterIP
