network:
  hostname: wieman.cloud
  externalIp: 85.148.81.86
  ipPool:
    - 192.168.178.201 - 192.168.178.210
  gateway:
    name: default-envoy-gateway
    listener: https
    namespace: envoy-gateway
    certificate:
      email: wiemanboy@gmail.com
      issuerRef:
        name: letsencrypt
        kind: ClusterIssuer
      hostnames:
        - "wieman.cloud"
        - "*.wieman.cloud"
        - "*.s3.wieman.cloud"
        - "wiemanboy.com"
        - "*.wiemanboy.com"
        - "jarnowieman.com"
        - "*.jarnowieman.com"
        - "jarnowieman.nl"
        - "*.jarnowieman.nl"
        - "carnaval.lol"
        - "*.carnaval.lol"
