apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres-cluster
spec:
  instances: 1

  bootstrap:
    {{ if not .Values.cnpg.restore }}
    initdb:
      database: keycloak
    {{ end }}
    {{ if .Values.cnpg.restore }}
    recovery:
      source: source
    {{ end }}

  storage:
    size: 2Gi

  {{ if not .Values.cnpg.restore }}
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: cnpg-backup-s3
  {{ end }}
  {{ if .Values.cnpg.restore }}
  externalClusters:
  - name: source
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: cnpg-backup-s3
        serverName: keycloak-postgres-cluster
  {{ end }}
