apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres-cluster
spec:
  instances: 1

  bootstrap:
    initdb:
      database: keycloak
    recovery:
      source: source

  storage:
    size: 2Gi

  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: cnpg-backup-s3

  externalClusters:
  - name: source
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: cnpg-backup-s3
        serverName: keycloak-postgres-cluster
