apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.db.host }}
spec:
  selector:
    app: postgresql-db
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-db
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          {{ with .Values.images.postgres.image -}}
          image: {{ .registry }}/{{ .repository }}:{{ .version }}
          {{ end -}}
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.db.username.secret }}
                  key: {{ .Values.keycloak.db.username.key }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.db.password.secret }}
                  key: {{ .Values.keycloak.db.password.key }}
            - name: POSTGRES_DB
              value: keycloak
            - name: PGDATA
              value: /data/pgdata
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        k8up.io/backup: "true"
      labels:
        next.wieman.cloud/workload: "postgres"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
