{{- with .Values.applications.argocd -}}
{{- if .deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  source:
    chart: argocd
    repoURL: {{ .Values.infrastructure.repository }}
    targetRevision: {{ .Values.infrastructure.argocd.version }}
    helm:
      valuesObject:
        argo-cd:
          configs:
            cm:
              url: https://argo.{{ $.Values.network.hostname }}
              oidc.config: |
                name: {{ .Values.auth.oidc.provider }}
                issuer: {{ .Values.auth.oidc.endpoint }}
                clientID: argocd
                clientSecret: $oidc.keycloak.clientSecret
                refreshTokenThreshold: 2m
                requestedScopes: ["openid", "profile", "email", "groups", "offline_access"]
          server:
            httproute:
              parentRefs:
              - name: {{ $.Values.network.gateway.name }}
                sectionName: {{ $.Values.network.gateway.listener }}
                namespace: {{ $.Values.network.gateway.namespace }}
              hostnames:
              - argo.{{ $.Values.network.hostname }}
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
{{- end -}}
{{- end -}}
