{{- if .Values.infrastructure.argocd.deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  source:
    chart: argocd
    repoURL: {{ .Values.infrastructure.repository }}
    targetRevision: {{ .Values.infrastructure.argocd.version }}
    helm:
      values: |
        environment: {{ toYaml .Values.environment | nindent 10 }}
        argo-cd:
          configs:
            cm:
              url: https://argo.{{ .Values.environment.hostname }}
              oidc.config: |
                name: Keycloak
                issuer: https://keycloak.{{ .Values.environment.hostname }}/realms/infrastructure
                clientID: argocd
                clientSecret: $oidc.keycloak.clientSecret
                requestedScopes: ["openid", "profile", "email", "groups", "offline_access"]
          server:
            httproute:
              parentRefs:
              - name: {{ .Values.environment.gateway.name }}
                sectionName: {{ .Values.environment.gateway.listener }}
                namespace: {{ .Values.environment.gateway.namespace }}
              hostnames:
              - argo.{{ .Values.environment.hostname }}
            grpcroute:
              parentRefs:
              - name: {{ .Values.environment.gateway.name }}
                sectionName: {{ .Values.environment.gateway.listener }}
                namespace: {{ .Values.environment.gateway.namespace }}
              hostnames:
              - argo.{{ .Values.environment.hostname }}
  destination:
    namespace: argocd
    server: {{ .Values.infrastructure.server }}
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
{{- end }}
