{{- with .Values.infrastructure.externalsecrets -}}
{{- if .deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: externalsecrets
  namespace: argocd
spec:
  source:
    chart: externalsecrets
    repoURL: {{ $.Values.infrastructure.repository }}
    targetRevision: {{ .version }}
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
{{- end -}}
{{- end -}}
