{{- with .Values.infrastructure.k8up -}}
{{- if .deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8up
  namespace: argocd
spec:
  source:
    chart: k8up
    repoURL: {{ $.Values.infrastructure.repository }}
    targetRevision: {{ .version }}
    helm:
      valuesObject:
        network: {{ toYaml $.Values.network | nindent 10 }}
        targetRepository: {{ toYaml $.Values.targetRepository | nindent 10 }}
        images: {{ toYaml $.Values.images | nindent 10 }}

        seaweedfs:
          endpoint: k8up.s3.{{ $.Values.network.hostname }}

  destination:
    namespace: k8up
    server: https://kubernetes.default.svc
  project: infrastructure
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec
        - /metadata/annotations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
{{- end -}}
{{- end -}}
