{{- if .Values.infrastructure.k8up.deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8up
  namespace: argocd
spec:
  source:
    chart: k8up
    repoURL: {{ .Values.infrastructure.repository }}
    targetRevision: {{ .Values.infrastructure.k8up.version }}
    helm:
      values: |
        environment: {{ toYaml .Values.environment | nindent 10 }}
        seaweedfs:
          endpoint: k8up.s3.{{ .Values.environment.hostname }}
        k8up:
          default: {{ toYaml .Values.infrastructure.k8up.default | nindent 12 }}
          {{- if .Values.infrastructure.k8up.backups }}
          backups: {{ toYaml .Values.infrastructure.k8up.backups | nindent 12 }}
          {{- end }}
          {{- if .Values.infrastructure.k8up.restores }}
          restores: {{ toYaml .Values.infrastructure.k8up.restores | nindent 12 }}
          {{- end }}
  destination:
    namespace: k8up
    server: {{ .Values.infrastructure.server }}
  project: infrastructure
  ignoreDifferences:
  - group: ""
    kind: Secret
    jqPathExpressions:
    - '.metadata.labels["wieman.cloud/random-secret"] != null'
    jsonPointers:
    - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
{{- end }}
