{{- with .Values.infrastructure.keycloak -}}
{{- if .deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  source:
    chart: keycloak
    repoURL: {{ $.Values.infrastructure.repository }}
    targetRevision: {{ .version }}
    helm:
      values: |
        network: {{ toYaml $.Values.network | nindent 10 }}
        backups: {{ toYaml $.Values.backups | nindent 10 }}
        restores: {{ toYaml .restores | nindent 10 }}
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
{{- end -}}
{{- end -}}
