{{- if .Values.infrastructure.keycloak.deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  source:
    chart: keycloak
    repoURL: {{ .Values.infrastructure.repository }}
    targetRevision: {{ .Values.infrastructure.keycloak.version }}
    helm:
      values: |
        environment: {{ toYaml .Values.environment | nindent 10 }}
        backups: {{ toYaml .Values.backups | nindent 10 }}
        restores: {{ toYaml .Values.infrastructure.keycloak.restores | nindent 10 }}
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
