{{- with .Values.infrastructure.metricsserver -}}
{{- if .deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metricsserver
  namespace: argocd
spec:
  source:
    chart: metricsserver
    repoURL: {{ $.Values.infrastructure.repository }}
    targetRevision: {{ .version }}

  destination:
    namespace: metrics-server
    server: https://kubernetes.default.svc
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
{{- end -}}
{{- end -}}
