{{- if .Values.infrastructure.prometheus.deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  source:
    chart: prometheus
    repoURL: {{ .Values.infrastructure.repository }}
    targetRevision: {{ .Values.infrastructure.prometheus.version }}
    helm:
      values: |
        environment: {{ toYaml .Values.environment | nindent 10 }}
  destination:
    namespace: prometheus
    server: {{ .Values.infrastructure.server }}
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
{{- end }}
