{{- if .Values.infrastructure.prometheus.deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  source:
    chart: prometheus
    repoURL: {{ .Values.infrastructure.repository }}
    targetRevision: {{ .Values.infrastructure.prometheus.version }}
    helm:
      values: |
        environment: {{ toYaml .Values.environment | nindent 10 }}
        kube-prometheus-stack:
          grafana:
            grafana.ini:
              auth.generic_oauth:
                name: {{ .Values.environment.oidc.provider }}
                auth_url: {{ .Values.environment.oidc.endpoint }}/protocol/openid-connect/auth
                token_url: {{ .Values.environment.oidc.endpoint }}/protocol/openid-connect/token
                api_url: {{ .Values.environment.oidc.endpoint }}/protocol/openid-connect/userinfo
  destination:
    namespace: prometheus
    server: {{ .Values.infrastructure.server }}
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
{{- end }}
