{{- with .Values.infrastructure.prometheus -}}
{{- if .deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  source:
    chart: prometheus
    repoURL: {{ $.Values.infrastructure.repository }}
    targetRevision: {{ .version }}
    helm:
      valuesObject:
        network: {{ toYaml $.Values.network | nindent 10 }}
        kube-prometheus-stack:
          grafana:
            grafana.ini:
              server:
                root_url: https://grafana.{{ $.Values.network.hostname }}
              auth.generic_oauth:
                name: {{ $.Values.auth.oidc.provider }}
                auth_url: {{ $.Values.auth.oidc.endpoint }}/protocol/openid-connect/auth
                token_url: {{ $.Values.auth.oidc.endpoint }}/protocol/openid-connect/token
                api_url: {{ $.Values.auth.oidc.endpoint }}/protocol/openid-connect/userinfo
            route:
              main:
                parentRefs:
                - name: {{ $.Values.network.gateway.name }}
                  sectionName: {{ $.Values.network.gateway.listener }}
                  namespace: {{ $.Values.network.gateway.namespace }}
                hostnames:
                - grafana.{{ $.Values.network.hostname }}
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
{{- end -}}
{{- end -}}
