{{- if .Values.infrastructure.rookceph.deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rookceph
  namespace: argocd
spec:
  source:
    chart: rookceph
    repoURL: {{ .Values.infrastructure.repository }}
    targetRevision: {{ .Values.infrastructure.rookceph.version }}
    helm:
      values: |
        environment: {{ toYaml .Values.environment | nindent 10 }}
        rook-ceph-cluster:
          operatorNamespace: rookceph-system
  destination:
    namespace: rookceph-system
    server: {{ .Values.infrastructure.server }}
{{- $defaults := .Values.infrastructure.defaults }}
{{- $cfg := merge $defaults (dict "syncPolicy" (merge $defaults.syncPolicy (dict "syncOptions" (append $defaults.syncPolicy.syncOptions "ServerSideApply=true")))) }}
{{- toYaml $cfg | nindent 2 }}
{{- end }}
