{{- with .Values.infrastructure.traefik -}}
{{- if .deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  source:
    chart: traefik
    repoURL: {{ $.Values.infrastructure.repository }}
    targetRevision: {{ .version }}
    helm:
      valuesObject:
        traefik:
          service:
            externalIps:
              - {{ $.Values.network.externalIp }}
            loadbalancerIp: 192.168.178.201
            annotations:
              external-dns.alpha.kubernetes.io/hostname: {{ $.Values.network.hostname }}
              external-dns.alpha.kubernetes.io/target: {{ $.Values.network.externalIp }}

          gateway:
            annotations:
              external-dns.alpha.kubernetes.io/target: {{ $.Values.network.hostname }}
  destination:
    namespace: gateway
    server: https://kubernetes.default.svc
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end -}}
{{- end -}}
