{{- if .Values.infrastructure.wireguard.deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: argocd
spec:
  source:
    chart: wireguard
    repoURL: {{ .Values.infrastructure.repository }}
    targetRevision: {{ .Values.infrastructure.wireguard.version }}
    helm:
      values: |
        environment: {{ toYaml .Values.environment | nindent 10 }}
        vpn: {{ toYaml .Values.vpn | nindent 10 }}
  destination:
    namespace: wireguard-system
    server: https://kubernetes.default.svc
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
