apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tofudeployer-aws-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws
  target:
    name: tofudeployer-aws-credentials
  data:
    - secretKey: accessKey
      remoteRef:
        key: tofudeployer-aws-credentials
        property: accessKey
    - secretKey: secretKey
      remoteRef:
        key: tofudeployer-aws-credentials
        property: secretKey
