apiVersion: v1
kind: ServiceAccount
metadata:
  name: forgejo-runner-controller
  namespace: {{ .Release.Namespace }}-runner-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: forgejo-runner-controller
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - create
      - list

  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs:
      - get
      - list
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: forgejo-runner-controller
  namespace: {{ .Release.Namespace }}-runner-system
subjects:
  - kind: ServiceAccount
    name: forgejo-runner-controller
    namespace: {{ .Release.Namespace }}-runner-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: forgejo-runner-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: forgejo-runner-controller
  name: forgejo-runner-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo-runner-controller
  template:
    metadata:
      labels:
        app: forgejo-runner-controller
    spec:
      serviceAccountName: forgejo-runner-controller
      containers:
      - name: controller
        {{ with .Values.images.forgejorunnercontroller.image -}}
        image: {{ .registry }}/{{ .repository }}:{{ .version }}
        {{ end -}}
        env:
          - name: DESIRED_RUNNERS
            value: "2"
          - name: RUNNER_SECRET_NAME
            value: test-secret
          - name: RUNNER_NAMESPACE
            value: {{ .Release.Namespace }}-runner-system
          - name: FORGEJO_NAMESPACE
            values: {{ .Release.Namespace}}
        resources: {}
