apiVersion: batch/v1
kind: Job
metadata:
  name: forgejo-runner-registration
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: forgejo-runner-registration
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      initContainers:
        - name: fix-permissions
          {{ with .Values.images.alpine.image }}
          image: {{ .registry }}/{{ .repository }}:{{ .version }}
          {{ end }}
          command:
            - sh
            - -c
            - |
              echo "Creating shared dir"
              mkdir -p /data/.runner
              chmod 775 /data/.runner

          volumeMounts:
            - name: forgejo-storage
              mountPath: /data

        - name: register
          {{ with .Values.images.forgejo.image }}
          image: {{ .registry }}/{{ .repository }}:{{ .version }}
          {{ end }}
          env:
            - name: GITEA_WORK_DIR
              value: "/data"
          command:
            - /bin/sh
            - -ec
            - |
              if [ ! -f /data/.runner/secret ]
              then
                echo "Generating secret"
                SECRET="$(tr -dc 'a-f0-9' </dev/urandom | head -c 40)"
                echo "${SECRET}" > /data/.runner/secret
              fi

              if [ -f /data/.runner/uuid ]
              then
                echo "Runner already configured"
                exit 0
              fi

              echo "Registering runner"
              {{ with .Values.runner.config }}
              forgejo forgejo-cli actions register \
                --name {{ .name }} \
                --secret "${SECRET}" \
                > /data/.runner/uuid 2>&1
              {{ end }}

              echo "Runner successfully registered: $(cat /data/.runner/uuid)"

          volumeMounts:
            - name: forgejo-storage
              mountPath: /data

      containers:
        - name: create-runner-secret
          {{ with .Values.images.kubectl.image }}
          image: {{ .registry }}/{{ .repository }}:{{ .version }}
          {{ end }}
          command:
            - /bin/sh
            - -ec
            - |
              echo "Creating/updating forgejo-runner secret in runner namespace"
              kubectl create secret generic forgejo-runner \
                --from-file=uuid=/data/.runner/uuid \
                --from-file=secret=/data/.runner/secret \
                -n {{ .Release.Namespace }}-runner-system \
                --dry-run=client -o yaml \
              | kubectl apply -f -

          volumeMounts:
            - name: forgejo-storage
              mountPath: /data

      volumes:
        - name: forgejo-storage
          persistentVolumeClaim:
            claimName: gitea-shared-storage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forgejo-runner-registration
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: forgejo-runner-registration
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: forgejo-runner-registration
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
subjects:
  - kind: ServiceAccount
    name: forgejo-runner-registration
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: forgejo-runner-registration
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: forgejo-runner-registration-secret
  namespace: {{ .Release.Namespace }}-runner-system
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: forgejo-runner-registration-secret
  namespace: {{ .Release.Namespace }}-runner-system
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
subjects:
  - kind: ServiceAccount
    name: forgejo-runner-registration
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: forgejo-runner-registration-secret
