apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
  namespace: infrastructure
spec:
  secretName: letsencrypt-secret
  dnsNames:
  - "wieman.cloud"
  - "*.wieman.cloud"
  - "wiemanboy.com"
  - "*.wiemanboy.com"
  - "jarnowieman.com"
  - "*.jarnowieman.com"
  - "jarnowieman.nl"
  - "*.jarnowieman.nl"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer