apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: local-backup-repo-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws
  target:
    name: local-backup-repo-password
  data:
    - secretKey: password
      remoteRef:
        key: local-backup-repo-password
        property: password
