apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: local-backup-s3-credentials
spec:
  length: 42
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: local-backup-s3-credentials
spec:
  target:
    name: local-backup-s3-credentials
  dataFrom:
  - sourceRef:
       generatorRef:
         apiVersion: generators.external-secrets.io/v1alpha1
         kind: Password
         name: local-backup-s3-credentials
    rewrite:
    - regexp:
        source: "(.*)"
        target: "access-key"

  - sourceRef:
       generatorRef:
         apiVersion: generators.external-secrets.io/v1alpha1
         kind: Password
         name: local-backup-s3-credentials
    rewrite:
    - regexp:
        source: "(.*)"
        target: "secret-key"
