apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.19.1
    helm:
      releaseName: cert-manager
      values: infrastructure/tls/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infrastructure
