apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
  namespace: infrastructure
spec:
  secretName: letsencrypt-secret
  dnsNames:
  - "*.localhost"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer