apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed
spec:
  image: chrislusf/seaweedfs:latest
  master:
    replicas: 1
    volumeSizeLimitMB: 1024
  volume:
    replicas: 1
    requests:
      storage: 2Gi
  filer:
    replicas: 1
    s3:
      enabled: true
      configSecret:
        name: test-secret
        key: seaweedfs_s3_config.json
    config: |
      [leveldb2]
      enabled = true
      dir = "/data/filerldb2"
