apiVersion: v1
kind: ConfigMap
metadata:
  name: app-install
data:
  app-install.sh: |
    # App installation:
    {{- range .Values.nextcloud.nextcloud.apps }}
    php occ app:install {{ .name }} || true
    php occ app:{{ ternary "enable" "disable" .enabled}} {{ .name }} || true
    {{- end }}
