{{- range $index, $backup := .Values.backups }}
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: {{ $backup.name }}
spec:
  backend:
    repoPasswordSecretRef:
      name: {{ $backup.repo.secret.name }}
      key: {{ $backup.repo.secret.key }}
    s3:
      endpoint: {{ $backup.s3.endpoint }}
      bucket: nextcloud-backups
      accessKeyIDSecretRef:
        name: {{ $backup.s3.secret.name }}
        key: {{ $backup.s3.secret.accessKey }}
      secretAccessKeySecretRef:
        name: {{ $backup.s3.secret.name }}
        key: {{ $backup.s3.secret.secretKey }}

  backup:
    schedule: {{ $backup.default.schedule.backup | quote }}
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 0
    podSecurityContext:
      runAsUser: 0
      fsGroup: 999
      fsGroupChangePolicy: OnRootMismatch
    labelSelectors:
      - matchExpressions:
        - key: workload
          operator: NotIn
          values:
            - nextcloud

  check:
    schedule: {{ $backup.default.schedule.check | quote }}

  prune:
    schedule: {{ $backup.default.schedule.prune | quote }}
    retention:
      keepLast: {{ $backup.default.retention.keepLast }}
      keepDaily: {{ $backup.default.retention.keepDaily }}
---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: {{ $backup.name }}-nextcloud
spec:
  backend:
    repoPasswordSecretRef:
      name: {{ $backup.repo.secret.name }}
      key: {{ $backup.repo.secret.key }}
    s3:
      endpoint: {{ $backup.s3.endpoint }}
      bucket: nextcloud-backups
      accessKeyIDSecretRef:
        name: {{ $backup.s3.secret.name }}
        key: {{ $backup.s3.secret.accessKey }}
      secretAccessKeySecretRef:
        name: {{ $backup.s3.secret.name }}
        key: {{ $backup.s3.secret.secretKey }}

  backup:
    schedule: {{ $backup.default.schedule.backup | quote }}
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 0
    podSecurityContext:
      runAsUser: 33
      fsGroup: 33
      fsGroupChangePolicy: OnRootMismatch
    labelSelectors:
      - matchExpressions:
        - key: workload
          operator: In
          values:
            - nextcloud

  check:
    schedule: {{ $backup.default.schedule.check | quote }}

  prune:
    schedule: {{ $backup.default.schedule.prune | quote }}
    retention:
      keepLast: {{ $backup.default.retention.keepLast }}
      keepDaily: {{ $backup.default.retention.keepDaily }}
---
{{- range $index, $restore := $.Values.restores }}
{{- if and ($restore.enabled) (eq $restore.fromBackup $backup.name) }}
apiVersion: k8up.io/v1
kind: Restore
metadata:
  name: {{ $restore.name }}
spec:
  podSecurityContext:
    fsGroup: 65532
    fsGroupChangePolicy: OnRootMismatch
  restoreMethod:
    folder:
      claimName: {{ $restore.claim.name }}
  {{- if ne ($restore.snapshot | default "") "" }}
  snapshot: {{ $restore.snapshot }}
  {{- end }}
  backend:
    repoPasswordSecretRef:
      name: {{ $backup.repo.secret.name }}
      key: {{ $backup.repo.secret.key }}
    s3:
      endpoint: {{ $backup.s3.endpoint }}
      bucket: nextcloud-backups
      accessKeyIDSecretRef:
        name: {{ $backup.s3.secret.name }}
        key: {{ $backup.s3.secret.accessKey }}
      secretAccessKeySecretRef:
        name: {{ $backup.s3.secret.name }}
        key: {{ $backup.s3.secret.secretKey }}
---
{{- end }}
{{- end }}
{{- end }}

