apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: default
spec:
  serviceAccountName: default
  containers:
    - name: debug
      image: alpine/kubectl:1.34.0
      command: ["/bin/sh"]
      args: ["-c", "sleep infinity"]
      stdin: true
      tty: true
  restartPolicy: Never
