apiVersion: v1
kind: ServiceAccount
metadata:
  name: debug-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: debug-sa-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: debug-sa
    namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: default
spec:
  serviceAccountName: debug-sa
  containers:
    - name: debug
      image: alpine/kubectl:1.34.0
      command: ["/bin/sh"]
      args: ["-c", "sleep infinity"]
      stdin: true
      tty: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
  restartPolicy: Never
