apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: {{ .Values.nextcloud.externalDatabase.host }}
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-db
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:18.1
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.nextcloud.externalDatabase.existingSecret.secretName }}
                  key: {{ .Values.nextcloud.externalDatabase.existingSecret.usernameKey }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.nextcloud.externalDatabase.existingSecret.secretName }}
                  key: {{ .Values.nextcloud.externalDatabase.existingSecret.passwordKey }}
            - name: POSTGRES_DB
              value: nextcloud
            - name: PGDATA
              value: /data/pgdata
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-postgresql-db-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-postgresql-db-0
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
{{- range $index, $backup := .Values.backups }}
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: {{ $backup.name }}
spec:
  backend:
    repoPasswordSecretRef:
      name: {{ $backup.repo.secret.name }}
      key: {{ $backup.repo.secret.key }}
    s3:
      endpoint: {{ $backup.s3.endpoint }}
      bucket: nextcloud-backups
      accessKeyIDSecretRef:
        name: {{ $backup.s3.secret.name }}
        key: {{ $backup.s3.secret.accessKey }}
      secretAccessKeySecretRef:
        name: {{ $backup.s3.secret.name }}
        key: {{ $backup.s3.secret.secretKey }}

  backup:
    schedule: {{ $backup.default.schedule.backup | quote }}
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 0
    podSecurityContext:
      runAsUser: 0
      fsGroup: 999
      fsGroupChangePolicy: OnRootMismatch

  check:
    schedule: {{ $backup.default.schedule.check | quote }}

  prune:
    schedule: {{ $backup.default.schedule.prune | quote }}
    retention:
      keepLast: {{ $backup.default.retention.keepLast }}
      keepDaily: {{ $backup.default.retention.keepDaily }}
---
{{- range $index, $restore := $.Values.restores }}
{{- if and ($restore.enabled) (eq $restore.fromBackup $backup.name) }}
apiVersion: k8up.io/v1
kind: Restore
metadata:
  name: {{ $restore.name }}
spec:
  podSecurityContext:
    fsGroup: 65532
    fsGroupChangePolicy: OnRootMismatch
  restoreMethod:
    folder:
      claimName: {{ $restore.claim.name }}
  backend:
    {{- if ne ($restore.snapshot | default "") "" }}
    snapshot: {{ $restore.snapshot }}
    {{- end }}
    repoPasswordSecretRef:
      name: {{ $backup.repo.secret.name }}
      key: {{ $backup.repo.secret.key }}
    s3:
      endpoint: {{ $backup.s3.endpoint }}
      bucket: nextcloud-backups
      accessKeyIDSecretRef:
        name: {{ $backup.s3.secret.name }}
        key: {{ $backup.s3.secret.accessKey }}
      secretAccessKeySecretRef:
        name: {{ $backup.s3.secret.name }}
        key: {{ $backup.s3.secret.secretKey }}
---
{{- end }}
{{- end }}
{{- end }}

