network:
  hostname: test.wieman.cloud
  externalIp: 0.0.0.0
  gateway:
    name: default-envoy-gateway
    listener: https
    namespace: envoygateway
    certificate:
      email: wiemanboy@gmail.com
      issuerRef:
        name: letsencrypt
        kind: ClusterIssuer
      hostnames:
        - "test.wieman.cloud"
