gateway-helm:
  deployment:
    envoyGateway:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 2m
          memory: 64Mi
  certgen:
    job:
      resources:
        limits:
          memory: 64Mi
        requests:
          cpu: 1m
          memory: 32Mi

network:
  hostname: test.wieman.cloud
  externalIp: 0.0.0.0
  gateway:
    name: example
    listener: example
    namespace: example
    certificate:
      email: email@example.com
      issuerRef:
        name: example
        kind: ClusterIssuer
      hostnames:
        - "example.com"
