apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: network
data:
  network:
    hostname: wieman.cloud
    gateway:
      name: default-envoy-gateway
      sectionName: https
      namespace: envoy-gateway
