apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret
            namespace: {{ .Release.Namespace }}
            key: access-key
          secretAccessKeySecretRef:
            name: aws-secret
            namespace: {{ .Release.Namespace }}
            key: secret-key
