apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: apps.wieman.cloud
spec:
  scope: Namespaced
  group: wieman.cloud
  names:
    kind: App
    plural: apps
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
     openAPIV3Schema:
       type: object
       properties:
        spec:
          type: object
          properties:
            image:
              description: The app's OCI container image.
              type: string

            route:
              type: object
              properties:
                subdomain:
                  description: The app's default subdomain. If empty defaults to name
                  type: string
                hostnames:
                  description: Additional hostnames
                  type: array
                  items:
                    type: string
                targetPort:
                  description: The app's exposed port
                  type: integer
                  default: 80

            resources:
              type: object
              properties:
                limits:
                  type: object
                  properties:
                    memory:
                      type: string
                requests:
                  type: object
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string

          required:
          - image
        status:
          type: object
          properties:
            replicas:
              description: The number of available app replicas.
              type: integer
            hostname:
              description: The app's default hostname.
              type: string
