environment:
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example

targetRepository:
  url: https://repo.git
  branch: example

tofudeployer:
  image:
    registry: example.com
    repository: products/tofudeployer
    version: 0.0.0

seaweedfs:
  name: backup-s3
  endpoint: k8up.s3.example.com
  secret:
    name: s3-config-secret

externalsecrets:
  k8sSecretStore:
    name: local-backup-s3-secret-store

k8up:
  k8up:
    skipWithoutAnnotation: true
