environment:
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example

seaweedfs:
  name: backup-s3
  endpoint: k8up.s3.example.com
  secret:
    name: s3-config-secret

k8up:
  k8up:
    skipWithoutAnnotation: true

  backend:
    repoPasswordSecretRef:
      name: repo-password-secret
      key: password

  default:
    schedule:
      backup: "*/5 * * * *"
      check: "0 1 * * 1"
      prune: "0 1 * * 0"
    retention:
      keepLast: 5
      keepDaily: 14
  # backups:
  # - name: example-backup
  #   namespace: default
  #   bucket: example-bucket
  #   schedule:
  #     backup: "*/5 * * * *"
  #     check: "0 1 * * 1"
  #     prune: "0 1 * * 0"
  #   retention:
  #     keepLast: 5
  #     keepDaily: 14

  # restores:
  # - name: example-restore
  #   namespace: default
  #   bucket: example-bucket
  #   snapshot: example-snapshot # Defaults to latest
  #   claim:
  #     name: example-pvc
  #     deploy: true
  #     backup: true
  #     spec:
  #       accessModes:
  #         - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 1Gi
