seaweedfs:
  name: backup-s3
  endpoint: k8up.s3.example.com
  secret:
    name: local-backup-s3-config

k8up:
  k8up:
    skipWithoutAnnotation: true

network:
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example
