external-dns:
  provider:
    name: cloudflare
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: api-token
  sources:
    - service
    - crd
    - gateway-grpcroute
    - gateway-httproute
    - gateway-tcproute
    - gateway-tlsroute
    - gateway-udproute

  resources:
    limits:
      memory: 72Mi
    requests:
      cpu: 1m
      memory: 56Mi
