{{- range $index, $backup := .Values.backups }}
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: {{ $backup.name }}
spec:
  backend:
    repoPasswordSecretRef:
      name: {{ $backup.repo.secret.name }}
      key: {{ $backup.repo.secret.key }}
    s3:
      endpoint: {{ $backup.s3.endpoint }}
      bucket: wiecloud-keycloak-backups
      accessKeyIDSecretRef:
        name: {{ $backup.s3.secret.name }}
        key: {{ $backup.s3.secret.accessKey }}
      secretAccessKeySecretRef:
        name: {{ $backup.s3.secret.name }}
        key: {{ $backup.s3.secret.secretKey }}

  backup:
    schedule: {{ $backup.default.schedule.backup | quote }}
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 0
    podSecurityContext:
      runAsUser: 0
      fsGroup: 999
      fsGroupChangePolicy: OnRootMismatch

  check:
    schedule: {{ $backup.default.schedule.check | quote }}

  prune:
    schedule: {{ $backup.default.schedule.prune | quote }}
    retention:
      keepLast: {{ $backup.default.retention.keepLast }}
      keepDaily: {{ $backup.default.retention.keepDaily }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $backup.s3.secret.name }}
spec:
  secretStoreRef: {{ $backup.s3.secret.storeRef | toYaml | nindent 4 }}
  target:
    name: {{ $backup.s3.secret.name }}
  data:
  - secretKey: {{ $backup.s3.secret.accessKey }}
    remoteRef:
      key: {{ $backup.s3.secret.name }}
      property: {{ $backup.s3.secret.accessKey }}

  - secretKey: {{ $backup.s3.secret.secretKey }}
    remoteRef:
      key: {{ $backup.s3.secret.name }}
      property: {{ $backup.s3.secret.secretKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $backup.repo.secret.name }}
spec:
  secretStoreRef: {{ $backup.repo.secret.storeRef | toYaml | nindent 4 }}
  target:
    name: {{ $backup.repo.secret.name }}
  data:
  - secretKey: {{ $backup.repo.secret.key }}
    remoteRef:
      key: {{ $backup.repo.secret.name }}
      property: {{ $backup.repo.secret.key }}
---
{{- range $index, $restore := $.Values.restores }}
{{- if and ($restore.enabled) (eq $restore.fromBackup $backup.name) }}
apiVersion: k8up.io/v1
kind: Restore
metadata:
  name: {{ $restore.name }}
spec:
  podSecurityContext:
    fsGroup: 65532
    fsGroupChangePolicy: OnRootMismatch
  restoreMethod:
    folder:
      claimName: {{ $restore.claim.name }}
  {{- if ne ($restore.snapshot | default "") "" }}
  snapshot: {{ $restore.snapshot }}
  {{- end }}
  backend:
    repoPasswordSecretRef:
      name: {{ $backup.repo.secret.name }}
      key: {{ $backup.repo.secret.key }}
    s3:
      endpoint: {{ $backup.s3.endpoint }}
      bucket: wiecloud-keycloak-backups
      accessKeyIDSecretRef:
        name: {{ $backup.s3.secret.name }}
        key: {{ $backup.s3.secret.accessKey }}
      secretAccessKeySecretRef:
        name: {{ $backup.s3.secret.name }}
        key: {{ $backup.s3.secret.secretKey }}
---
{{- end }}
{{- end }}
{{- end }}

