apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws
  target:
    name: keycloak-db-credentials
  data:
    - secretKey: username
      remoteRef:
        key: keycloak-db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: keycloak-db-credentials
        property: password
