apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.db.host }}
spec:
  selector:
    app: postgresql-db
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-db
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:18.1
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.db.username.secret }}
                  key: {{ .Values.keycloak.db.username.key }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.db.password.secret }}
                  key: {{ .Values.keycloak.db.password.key }}
            - name: POSTGRES_DB
              value: keycloak
            - name: PGDATA
              value: /data/pgdata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-postgresql-db-0
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
{{- range $index, $backup := .Values.backups }}
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: {{ $backup.name }}
spec:
  backend:
    repoPasswordSecretRef:
      name: {{ $backup.repo.secret.name }}
      key: {{ $backup.repo.secret.key }}
    s3:
      endpoint: {{ $backup.s3.endpoint }}
      bucket: keycloak-backups
      accessKeyIDSecretRef:
        name: {{ $backup.s3.secret.name }}
        key: {{ $backup.s3.secret.accessKey }}
      secretAccessKeySecretRef:
        name: {{ $backup.s3.secret.name }}
        key: {{ $backup.s3.secret.secretKey }}

  backup:
    schedule: {{ $backup.default.schedule.backup | quote }}
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 0
    podSecurityContext:
      runAsUser: 0
      fsGroup: 999
      fsGroupChangePolicy: OnRootMismatch

  check:
    schedule: {{ $backup.default.schedule.check | quote }}

  prune:
    schedule: {{ $backup.default.schedule.prune | quote }}
    retention:
      keepLast: {{ $backup.default.retention.keepLast }}
      keepDaily: {{ $backup.default.retention.keepDaily }}
---
{{- end }}
