apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-secret-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: client-secret-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
    {{- range $index, $permission := .Values.keycloak.clientCreationPermissions }}
      - {{ printf "%s-client-secret" $permission.name | quote }}
    {{- end }}
    verbs: ["create", "get", "list", "watch", "update", "patch"]

---
{{- range $index, $permission := .Values.keycloak.clientCreationPermissions }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-client-secret-manager" $permission.name | quote }}
  namespace: {{ $permission.namespace }}
subjects:
  - kind: ServiceAccount
    name: client-secret-manager
    namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: client-secret-manager
---
{{ end -}}
