network:
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example

vpn:
  peers:
    - peer1
    - peer2
  dns:
    - "0.0.0.0"
    - "0.0.0.1"

images:
  wireguardserver:
    image:
      registry: example.com
      repository: linuxserver/wireguard
      version: 0.0.0

backups:
  - name: local
    s3:
      endpoint: https://k8up.s3.wieman.cloud
      secret:
        name: local-backup-s3-credentials
        accessKey: accessKey
        secretKey: secretKey
        storeRef:
          kind: ClusterSecretStore
          name: local-backup-s3-credentials-store
    repo:
      secret:
        name: local-backup-repo-password
        key: password
        storeRef:
          kind: ClusterSecretStore
          name: local-backup-repo-password-store
    default:
      schedule:
        backup: "0 12 * * *"
        check: "30 12 * * *"
        prune: "0 13 * * *"
      retention:
        keepLast: 5
        keepDaily: 14
  - name: aws
    s3:
      endpoint: https://s3.eu-central-1.amazonaws.com
      secret:
        name: aws-backup-s3-credentials
        accessKey: accessKey
        secretKey: secretKey
        storeRef:
          kind: ClusterSecretStore
          name: aws
    repo:
      secret:
        name: aws-backup-repo-password
        key: password
        storeRef:
          kind: ClusterSecretStore
          name: aws
    default:
      schedule:
        backup: "0 0 * * *"
        check: "30 0 * * *"
        prune: "0 1 * * *"
      retention:
        keepLast: 5
        keepDaily: 14
