apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
spec:
  serviceSelector:
    matchLabels:
      expose: l2
  interfaces:
    - ^ens18$
  loadBalancerIPs: true
