apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: nextcloud-maintenance-on
spec:
  backupCommand: >
    sh -c 'php occ maintenance:mode --on'
  pod:
    spec:
      containers:
        - name: nextcloud-maintenance
          image: nextcloud:apache
          command: ["sleep", "infinity"]
          securityContext:
            runAsUser: 33
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-nextcloud
---
apiVersion: k8up.io/v1
kind: PostBackupPod
metadata:
  name: nextcloud-maintenance-off
spec:
  backupCommand: >
    sh -c 'php occ maintenance:mode --off'
  pod:
    spec:
      containers:
        - name: nextcloud-maintenance
          image: nextcloud:apache
          command: ["sleep", "infinity"]
          securityContext:
            runAsUser: 33
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-nextcloud
