apiVersion: v2
name: forgejo
type: application
version: 0.0.0
dependencies:
  - name: shared
    version: 0.0.0
    repository: oci://harbor.wieman.cloud/products
  - name: forgejo
    version: 17.1.4
    repository: oci://code.forgejo.org/forgejo-helm
