forgejo:
  replicaCount: 3
  gitea:
    config:
      APP_NAME: 'Forgejo'

      database:
        DB_TYPE: postgres
        HOST: forgejo-postgres-cluster-rw

      queue:
        TYPE: redis
        CONN_STR: redis://forgejo-dragonfly:6379/0

      cache:
        ADAPTER: redis
        HOST: redis://forgejo-dragonfly:6379/0

      session:
        PROVIDER: redis
        PROVIDER_CONFIG: redis://forgejo-dragonfly:6379/0

    # oauth:
    #   - name: example
    #     provider: openidConnect
    #     autoDiscoverUrl: https://example.com/.well-known/openid-configuration

    additionalConfigFromEnvs:
      - name: FORGEJO__DATABASE__NAME
        valueFrom:
          secretKeyRef:
            name: forgejo-postgres-cluster-app
            key: dbname
      - name: FORGEJO__DATABASE__USER
        valueFrom:
          secretKeyRef:
            name: forgejo-postgres-cluster-app
            key: username
      - name: FORGEJO__DATABASE__PASSWD
        valueFrom:
          secretKeyRef:
            name: forgejo-postgres-cluster-app
            key: password

      - name: GITEA_OAUTH_KEY_0
        value: forgejo
      - name: GITEA_OAUTH_SECRET_0
        valueFrom:
          secretKeyRef:
            name: forgejo-client-secret
            key: secret

  strategy:
    type: RollingUpdate

  httpRoute:
    enabled: true
    parentRefs:
      - name: example
        sectionName: https
        namespace: example
    hostnames:
      - forgejo.example.com

  tcpRoute:
    enabled: true
    parentRefs:
      - name: example
        sectionName: ssh
        namespace: example

  persistence:
    enabled: true
    accessModes:
      - ReadWriteMany
    size: 10Gi
    annotations:
      k8up.io/backup: "true"

  # extraVolumes:
  #   - name: forgejo-themes
  #     secret:
  #       secretName: forgejo-themes

  # extraVolumeMounts:
  #   - name: forgejo-themes
  #     readOnly: true
  #     mountPath: '/data/gitea/public/assets/css'

cnpg:
  restore: false
