{{- with .Values.network.gateway.certificate }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .issuerRef.name }}
spec:
  acme:
    email: {{ .email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-api-token
    solvers:
    - dns01:
        cloudflare:
          email: {{ .email }}
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
{{- end -}}
