environment:
  hostname: example.com
  gateway:
    name: traefik-gateway
    listener: websecure
    namespace: gateway

harbor:
  persistence:
    persistentVolumeClaim:
      registry:
        size: 10Gi
  expose:
    type: NodePort
    tls:
      enabled: false
  externalURL: https://harbor.example.com
