harbor:
  persistence:
    persistentVolumeClaim:
      database:
        annotations:
          k8up.io/backup: "true"
      registry:
        size: 10Gi
        annotations:
          k8up.io/backup: "true"
  expose:
    type: route
    route:
      parentRefs: []
      hosts: []
  externalURL: https://harbor.example.com
