{{- if .Values.applications.minecraft.deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
spec:
  source:
    chart: minecraft
    repoURL: {{ .Values.applications.repository }}
    targetRevision: {{ .Values.applications.minecraft.version }}
    helm:
      values: |
        environment: {{ toYaml .Values.environment | nindent 10 }}
        backups: {{ toYaml .Values.backups | nindent 10 }}
        restores: {{ toYaml .Values.applications.minecraft.restores | nindent 10 }}
        rconcli: {{ toYaml .Values.images.rconcli | nindent 10 }}
        minecraft:
          minecraftServer:
            worldSaveName: {{ .Values.applications.minecraft.world.name }}
            version: {{ .Values.applications.minecraft.world.version }}
            type: {{ .Values.applications.minecraft.launcher }}
            vanillaTweaksShareCodes: {{ toYaml .Values.applications.minecraft.mods.vanillaTweaks | nindent 16 }}
            modrinth:
              projects: {{ toYaml .Values.applications.minecraft.mods.modrinth.projects | nindent 16 }}
            autoCurseForge:
              pageUrl: {{ .Values.applications.minecraft.mods.curseforge.pageUrl }}
              excludeMods: {{ toYaml .Values.applications.minecraft.mods.curseforge.excludeMods | nindent 16 }}
              includeMods: {{ toYaml .Values.applications.minecraft.mods.curseforge.includeMods | nindent 16 }}
          extraEnv:
            CURSEFORGE_FILES: | {{- .Values.applications.minecraft.bluemap.file | nindent 14 }}
            {{- if .Values.applications.minecraft.mods.curseforge.manifest.deploy}}
            CF_MODPACK_MANIFEST: /manifests/manifest.json
            CF_SLUG: "custom"
            {{- end}}
        curseforge:
          {{- if .Values.applications.minecraft.mods.curseforge.manifest.deploy}}
          modManifest: | {{ .Files.Get "files/minecraft/mod-manifest.json" | nindent 12 }}
          {{- end}}
  destination:
    namespace: minecraft
    server: {{ .Values.applications.server }}
  project: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
