{{- with .Values.applications.minecraft -}}
{{- if .deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
spec:
  source:
    chart: minecraft
    repoURL: {{ $.Values.applications.repository }}
    targetRevision: {{ .version }}
    helm:
      valuesObject:
        network: {{ toYaml $.Values.network | nindent 10 }}
        images: {{ toYaml $.Values.images | nindent 10 }}
        backups: {{ toYaml $.Values.backups | nindent 10 }}
        restores: {{ toYaml .restores | nindent 10 }}

        minecraft:
          image:
            tag: {{ .server.version }}
          minecraftServer:
            worldSaveName: {{ .world.name }}
            version: {{ .world.version }}
            type: {{ .server.launcher }}
            vanillaTweaksShareCodes: {{ toYaml .mods.vanillaTweaks | nindent 16 }}
            modrinth:
              projects: {{ toYaml .mods.modrinth.projects | nindent 16 }}
            autoCurseForge:
              pageUrl: {{ .mods.curseforge.pageUrl }}
              zipUrl: {{ .mods.curseforge.zip.file }}
              excludeMods: {{ toYaml .mods.curseforge.excludeMods | nindent 16 }}
              includeMods: {{ toYaml .mods.curseforge.includeMods | nindent 16 }}

          extraEnv:
            CURSEFORGE_FILES: |
              {{- .bluemap.file | nindent 14 }}

            {{- if .mods.curseforge.zip.deploy}}
            CF_MODPACK_ZIP: /data/zip/server.zip
            CF_SLUG: "custom"
            {{- end}}

  destination:
    namespace: minecraft
    server: https://kubernetes.default.svc
  project: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
{{- end -}}
{{- end -}}
