{{- with .Values.applications.nextcloud -}}
{{- if .deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  source:
    chart: nextcloud
    repoURL: {{ $.Values.applications.repository }}
    targetRevision: {{ .version }}
    helm:
      valuesObject:
        network: {{ toYaml $.Values.network | nindent 10 }}
        auth: {{ toYaml $.Values.auth | nindent 10 }}
        images: {{ toYaml $.Values.images | nindent 10 }}
        backups: {{ toYaml $.Values.backups | nindent 10 }}
        restores: {{ toYaml .restores | nindent 10 }}

        nextcloud:
          nextcloud:
            host: next.{{ $.Values.network.hostname }}

  destination:
    namespace: nextcloud
    server: https://kubernetes.default.svc
  project: applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
{{- end -}}
{{- end -}}
