{{- with .Values.applications.website -}}
{{- if .deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ $.Values.targetRepository.url }}
    targetRevision: {{ $.Values.targetRepository.branch }}
    path: applications/website
  destination:
    server: https://kubernetes.default.svc
    namespace: website
  project: applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
{{- end -}}
{{- end -}}
