keycloak:
  db:
    vendor: postgres
    host: keycloak-postgres-cluster-rw
    username:
      secret: keycloak-postgres-cluster-app
      key: username
    password:
      secret: keycloak-postgres-cluster-app
      key: password
  clientCreationPermissions:
    - name: argocd
      namespace: argocd
    - name: harbor
      namespace: harbor
    - name: nextcloud
      namespace: nextcloud
    - name: grafana
      namespace: prometheus

cnpg:
  restore: false

tofudeployer:
  dryRun: false

network:
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example

targetRepository:
  url: https://repo.git
  branch: example

images:
  keycloakserver:
    image:
      registry: example.com
      repository: keycloak/keycloak
      version: 26.6.2

  tofudeployer:
    image:
      registry: example.com
      repository: products/tofudeployer
      version: 0.0.0
