longhorn:
  persistence:
    dataEngine: "V2"
  longhornManager:
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 384Mi

network:
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example

auth:
  basic:
    name: example-auth
    secret:
      name: example-auth-secret
