argo-cd:
  configs:
    params:
      server.insecure: true
      controller.diff.server.side: true
    cm:
      admin.enabled: "false"
      url: https://argo.example.com
      exec.enabled: true
      oidc.config: "overwritten"

      resource.customizations.actions.k8up.io_Schedule: |
        discovery.lua: |
          actions = {}

          actions["create-backup"] = {["disabled"] = true}
          actions["create-check"] = {["disabled"] = true}
          actions["create-prune"] = {["disabled"] = true}

          if obj.spec.backup ~= nil then
              actions["create-backup"]["disabled"] = false
          end
          if obj.spec.check ~= nil then
              actions["create-check"]["disabled"] = false
          end
          if obj.spec.prune ~= nil then
              actions["create-prune"]["disabled"] = false
          end

          return actions

        definitions:
        - name: create-backup
          displayName: Create Backup
          action.lua: |
            local backup = {
              apiVersion = "k8up.io/v1",
              kind = "Backup",
              metadata = {
                generateName = obj.metadata.name .. "-backup-",
                namespace = obj.metadata.namespace,
                ownerReferences = {
                  {
                    apiVersion = obj.apiVersion,
                    kind = obj.kind,
                    name = obj.metadata.name,
                    uid = obj.metadata.uid
                  }
                }
              },
              spec = obj.spec.backup
            }

            backup.spec.backend = obj.spec.backend

            return {
              {
                operation = "create",
                resource = backup
              }
            }

        - name: create-check
          displayName: Create Check
          action.lua: |
            local check = {
              apiVersion = "k8up.io/v1",
              kind = "Check",
              metadata = {
                generateName = obj.metadata.name .. "-check-",
                namespace = obj.metadata.namespace,
                ownerReferences = {
                  {
                    apiVersion = obj.apiVersion,
                    kind = obj.kind,
                    name = obj.metadata.name,
                    uid = obj.metadata.uid
                  }
                }
              },
              spec = obj.spec.check
            }

            check.spec.backend = obj.spec.backend

            return {
              {
                operation = "create",
                resource = check
              }
            }

        - name: create-prune
          displayName: Create Prune
          action.lua: |
            local prune = {
              apiVersion = "k8up.io/v1",
              kind = "Prune",
              metadata = {
                generateName = obj.metadata.name .. "-prune-",
                namespace = obj.metadata.namespace,
                ownerReferences = {
                  {
                    apiVersion = obj.apiVersion,
                    kind = obj.kind,
                    name = obj.metadata.name,
                    uid = obj.metadata.uid
                  }
                }
              },
              spec = obj.spec.prune
            }

            prune.spec.backend = obj.spec.backend

            return {
              {
                operation = "create",
                resource = prune
              }
            }

    rbac:
      policy.csv: |
        g, /infra/argocd/admin, role:admin
        g, /infra/argocd/reader, role:readonly

  server:
    httproute:
      enabled: true
      parentRefs:
        - name: example-gateway
          sectionName: web-example
          namespace: example
      hostnames:
        - argo.example.com

    resources:
      limits:
        memory: 256Gi
      requests:
        cpu: 15m
        memory: 128Mi

  controller:
    resources:
      limits:
        memory: 1536Mi
      requests:
        cpu: 250m
        memory: 768Mi

  repoServer:
    resources:
      limits:
        memory: 512Gi
      requests:
        cpu: 50m
        memory: 256Mi

  redis:
    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 5m
        memory: 32Mi

  applicationSet:
    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 2m
        memory: 32Mi

  dex:
    enabled: false

  notifications:
    enabled: false
