environment:
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example

argo-cd:
  configs:
    params:
      server.insecure: true
    cm:
      admin.enabled: "false"
      url: https://argo.example.com
      exec.enabled: true
      oidc.config: "overwritten"
    rbac:
      policy.default: role:readonly
      policy.csv: |
        g, /infra/admin, role:admin
  server:
    httproute:
      enabled: true
      parentRefs:
      - name: example-gateway
        sectionName: web-example
        namespace: example
      hostnames:
      - argo.example.com
    grpcroute:
      enabled: true
      parentRefs:
      - name: example-gateway
        sectionName: web-example
        namespace: example
      hostnames:
      - argo.example.com
