apiVersion: v1
kind: ServiceAccount
metadata:
  name: update-forgejo-oidc-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: update-forgejo-oidc-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - forgejo-oidc-client
    verbs:
      - get
      - patch

  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: update-forgejo-oidc-secret
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: update-forgejo-oidc-secret
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: update-forgejo-oidc-secret
---
apiVersion: batch/v1
kind: Job
metadata:
  name: update-forgejo-oidc-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: update-forgejo-oidc-secret
      restartPolicy: Never
      containers:
        - name: update-forgejo-oidc-secret
          image: alpine/kubectl:1.34.0
          env:
            - name: CLIENT_ID
              value: forgejo

            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: forgejo-client-secret
                  key: secret

          command:
            - /bin/sh
            - -c
            - |
              set -eu

              kubectl create secret generic forgejo-oidc-client \
                --namespace {{ .Release.Namespace }} \
                --from-literal=key="${CLIENT_ID}" \
                --from-literal=secret="${CLIENT_SECRET}" \
                --dry-run=client \
                -o yaml |
                kubectl apply -f -
