name: Build forgejorunnercontroller

on:
  pull_request:
    branches:
    - master
    paths:
    - products/forgejorunnercontroller/image**
    - .github/workflows/image_build_forgejorunnercontroller.yaml
    - .github/workflows/image_build.yaml
    - pipeline/build/scripts/image/**

jobs:
  build:
    name: Build
    uses: ./.github/workflows/image_build.yaml
    with:
      image_name: forgejorunnercontroller
      image_path: products/forgejorunnercontroller/image
      registry: harbor.wieman.cloud
      repository: products
    secrets:
      registry_username: ${{ secrets.OCI_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.OCI_REGISTRY_PASSWORD }}
      app_client_id: ${{ secrets.APP_CLIENT_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
